version: '3'
services:
  practice:
    container_name: practice
    image: postgres:12.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: nebocco
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
    - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    logging:
      options:
        max-size: "10k"
        max-file: "5"